framework:
    messenger:
        transports:
            amqp_invite_creation: '%env(MESSENGER_TRANSPORT_DSN)%/invites'
            amqp_events: '%env(MESSENGER_TRANSPORT_DSN)%/events'

        routing:
            App\Message\CreateInvitations: amqp_invite_creation
            App\Message\InvitationRedeemed: amqp_events

        buses:
            default:
                middleware:
                    - 'doctrine_transaction_middleware'

